services:
  - type: web
    name: telegram-challenge-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
